project_id = "iago-shopping"

[functions.payment-engine]
verify_jwt = false

[functions.payment-create]
verify_jwt = false

[functions.payment-sync]
verify_jwt = false

[functions.payment-cancel]
verify_jwt = false

[functions.mercado-pago-webhook]
verify_jwt = false
