-- Fase 8 - Pedidos.
--
-- Escopo:
-- - converter o carrinho ativo do usuario autenticado em pedido;
-- - registrar snapshot dos itens no momento do pedido;
-- - baixar estoque por venda ao finalizar o pedido;
-- - listar pedidos do cliente e pedidos recebidos no admin;
-- - sem pagamentos, gateway, Pix ou cartao nesta fase.

do $$
begin
  create type public.shopping_status_pedido as enum (
    'pendente_pagamento',
    'cancelado'
  );
exception
  when duplicate_object then null;
end;
$$;

create table if not exists public.shopping_pedidos (
  id uuid primary key default gen_random_uuid(),
  numero bigint generated by default as identity unique,
  user_id uuid not null references auth.users(id) on delete cascade,
  perfil_id uuid references public.shopping_perfis(id) on delete set null,
  carrinho_id uuid references public.shopping_carrinhos(id) on delete set null,
  status public.shopping_status_pedido not null default 'pendente_pagamento',
  cliente_nome text,
  cliente_email text,
  subtotal numeric(12, 2) not null default 0,
  total numeric(12, 2) not null default 0,
  moeda text not null default 'BRL',
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  constraint shopping_pedidos_total_non_negative check (total >= 0),
  constraint shopping_pedidos_subtotal_non_negative check (subtotal >= 0)
);

create index if not exists idx_shopping_pedidos_user_data
  on public.shopping_pedidos (user_id, criado_em desc);

create index if not exists idx_shopping_pedidos_status_data
  on public.shopping_pedidos (status, criado_em desc);

create table if not exists public.shopping_pedido_itens (
  id uuid primary key default gen_random_uuid(),
  pedido_id uuid not null references public.shopping_pedidos(id) on delete cascade,
  produto_id uuid references public.shopping_produtos(id) on delete set null,
  variacao_id uuid references public.shopping_produto_variacoes(id) on delete set null,
  sku text not null,
  nome text not null,
  marca text not null,
  categoria text not null,
  imagem_url text,
  quantidade integer not null,
  preco_unitario numeric(12, 2) not null,
  subtotal numeric(12, 2) not null,
  criado_em timestamptz not null default now(),
  constraint shopping_pedido_itens_quantidade_positive check (quantidade > 0),
  constraint shopping_pedido_itens_preco_non_negative check (preco_unitario >= 0),
  constraint shopping_pedido_itens_subtotal_non_negative check (subtotal >= 0)
);

create index if not exists idx_shopping_pedido_itens_pedido
  on public.shopping_pedido_itens (pedido_id, criado_em, id);

drop trigger if exists trg_shopping_pedidos_touch on public.shopping_pedidos;
create trigger trg_shopping_pedidos_touch
before update on public.shopping_pedidos
for each row execute function public.shopping_touch_atualizado_em();

alter table public.shopping_pedidos enable row level security;
alter table public.shopping_pedido_itens enable row level security;

drop policy if exists shopping_pedidos_select_own_or_admin on public.shopping_pedidos;
create policy shopping_pedidos_select_own_or_admin
on public.shopping_pedidos
for select
to authenticated
using (
  user_id = auth.uid()
  or public.shopping_is_admin(auth.uid())
);

drop policy if exists shopping_pedido_itens_select_own_or_admin on public.shopping_pedido_itens;
create policy shopping_pedido_itens_select_own_or_admin
on public.shopping_pedido_itens
for select
to authenticated
using (
  exists (
    select 1
    from public.shopping_pedidos sp
    where sp.id = pedido_id
      and (
        sp.user_id = auth.uid()
        or public.shopping_is_admin(auth.uid())
      )
  )
);

revoke all on public.shopping_pedidos from anon, authenticated;
revoke all on public.shopping_pedido_itens from anon, authenticated;
grant select on public.shopping_pedidos to authenticated;
grant select on public.shopping_pedido_itens to authenticated;

create or replace function public.shopping_pedido_finalizar_carrinho()
returns public.shopping_pedidos
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := public.shopping_carrinho_assert_user();
  v_perfil public.shopping_perfis;
  v_carrinho public.shopping_carrinhos;
  v_pedido public.shopping_pedidos;
  v_item record;
  v_variacao public.shopping_produto_variacoes;
  v_saldo_anterior integer;
  v_total numeric(12, 2);
  v_total_itens integer;
begin
  select *
  into v_perfil
  from public.shopping_perfis sp
  where sp.user_id = v_user_id
  limit 1;

  select *
  into v_carrinho
  from public.shopping_carrinhos sc
  where sc.user_id = v_user_id
    and sc.status = 'ativo'::public.shopping_status_carrinho
  for update;

  if v_carrinho.id is null then
    raise exception 'Carrinho ativo nao encontrado para finalizar pedido.';
  end if;

  select
    count(*)::integer,
    coalesce(sum(sci.preco_unitario * sci.quantidade), 0)::numeric(12, 2)
  into v_total_itens, v_total
  from public.shopping_carrinho_itens sci
  where sci.carrinho_id = v_carrinho.id;

  if v_total_itens = 0 then
    raise exception 'Carrinho vazio nao pode gerar pedido.';
  end if;

  insert into public.shopping_pedidos (
    user_id,
    perfil_id,
    carrinho_id,
    status,
    cliente_nome,
    cliente_email,
    subtotal,
    total
  )
  values (
    v_user_id,
    v_perfil.id,
    v_carrinho.id,
    'pendente_pagamento'::public.shopping_status_pedido,
    v_perfil.nome_exibicao,
    v_perfil.email_normalizado,
    v_total,
    v_total
  )
  returning * into v_pedido;

  for v_item in
    select
      sci.produto_id,
      sci.quantidade,
      sci.preco_unitario,
      sp.sku,
      sp.nome,
      sp.marca,
      sp.categoria,
      sp.status,
      si.imagem_url
    from public.shopping_carrinho_itens sci
    join public.shopping_produtos sp on sp.id = sci.produto_id
    left join lateral (
      select spi.url as imagem_url
      from public.shopping_produto_imagens spi
      where spi.produto_id = sp.id
      order by spi.principal desc, spi.ordem, spi.id
      limit 1
    ) si on true
    where sci.carrinho_id = v_carrinho.id
    order by sci.criado_em, sci.id
  loop
    if v_item.status <> 'publicado'::public.shopping_status_produto then
      raise exception 'Produto indisponivel para gerar pedido.';
    end if;

    select *
    into v_variacao
    from public.shopping_produto_variacoes spv
    where spv.produto_id = v_item.produto_id
      and spv.ativo
    order by spv.principal desc, spv.id
    limit 1
    for update;

    if v_variacao.id is null then
      raise exception 'Produto sem variacao de estoque para pedido.';
    end if;

    if v_variacao.estoque_atual < v_item.quantidade then
      raise exception 'Quantidade solicitada maior que o estoque disponivel.';
    end if;

    v_saldo_anterior := v_variacao.estoque_atual;

    update public.shopping_produto_variacoes
    set estoque_atual = estoque_atual - v_item.quantidade,
        atualizado_por = auth.uid()
    where id = v_variacao.id
      and estoque_atual >= v_item.quantidade
    returning * into v_variacao;

    if v_variacao.id is null then
      raise exception 'Estoque mudou durante a finalizacao do pedido.';
    end if;

    insert into public.shopping_pedido_itens (
      pedido_id,
      produto_id,
      variacao_id,
      sku,
      nome,
      marca,
      categoria,
      imagem_url,
      quantidade,
      preco_unitario,
      subtotal
    )
    values (
      v_pedido.id,
      v_item.produto_id,
      v_variacao.id,
      v_item.sku,
      v_item.nome,
      v_item.marca,
      v_item.categoria,
      v_item.imagem_url,
      v_item.quantidade,
      v_item.preco_unitario,
      (v_item.preco_unitario * v_item.quantidade)::numeric(12, 2)
    );

    insert into public.shopping_estoque_movimentos (
      variacao_id,
      produto_id,
      tipo,
      quantidade,
      saldo_anterior,
      saldo_posterior,
      motivo,
      criado_por
    )
    values (
      v_variacao.id,
      v_item.produto_id,
      'venda'::public.shopping_tipo_movimento_estoque,
      -v_item.quantidade,
      v_saldo_anterior,
      v_variacao.estoque_atual,
      'Baixa de estoque pela finalizacao de pedido da Fase 8 do IAGO Shopping.',
      auth.uid()
    );
  end loop;

  update public.shopping_carrinhos
  set status = 'convertido'::public.shopping_status_carrinho
  where id = v_carrinho.id;

  insert into public.shopping_auditoria (
    ator_user_id,
    acao,
    tabela,
    registro_id,
    antes,
    depois,
    motivo
  )
  values (
    auth.uid(),
    'pedido.finalizar',
    'shopping_pedidos',
    v_pedido.id,
    jsonb_build_object('carrinho_id', v_carrinho.id),
    to_jsonb(v_pedido),
    'Pedido criado a partir do carrinho ativo pela Fase 8 do IAGO Shopping.'
  );

  return v_pedido;
end;
$$;

create or replace function public.shopping_pedidos_cliente_listar()
returns table (
  id uuid,
  numero bigint,
  status public.shopping_status_pedido,
  total numeric,
  moeda text,
  itens jsonb,
  criado_em timestamptz,
  atualizado_em timestamptz
)
language sql
stable
security definer
set search_path = public
as $$
  select
    sp.id,
    sp.numero,
    sp.status,
    sp.total,
    sp.moeda,
    coalesce(si.itens, '[]'::jsonb) as itens,
    sp.criado_em,
    sp.atualizado_em
  from public.shopping_pedidos sp
  left join lateral (
    select jsonb_agg(
      jsonb_build_object(
        'item_id', spi.id,
        'produto_id', spi.produto_id,
        'sku', spi.sku,
        'nome', spi.nome,
        'marca', spi.marca,
        'categoria', spi.categoria,
        'imagem_url', spi.imagem_url,
        'quantidade', spi.quantidade,
        'preco_unitario', spi.preco_unitario,
        'subtotal', spi.subtotal
      )
      order by spi.criado_em, spi.id
    ) as itens
    from public.shopping_pedido_itens spi
    where spi.pedido_id = sp.id
  ) si on true
  where sp.user_id = auth.uid()
  order by sp.criado_em desc, sp.numero desc;
$$;

create or replace function public.shopping_admin_listar_pedidos()
returns table (
  id uuid,
  numero bigint,
  status public.shopping_status_pedido,
  cliente_nome text,
  cliente_email text,
  total numeric,
  moeda text,
  itens jsonb,
  criado_em timestamptz,
  atualizado_em timestamptz
)
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_perfil public.shopping_perfis := public.shopping_admin_assert_produtos_permitido();
begin
  return query
  select
    sp.id,
    sp.numero,
    sp.status,
    sp.cliente_nome,
    sp.cliente_email,
    sp.total,
    sp.moeda,
    coalesce(si.itens, '[]'::jsonb) as itens,
    sp.criado_em,
    sp.atualizado_em
  from public.shopping_pedidos sp
  left join lateral (
    select jsonb_agg(
      jsonb_build_object(
        'item_id', spi.id,
        'sku', spi.sku,
        'nome', spi.nome,
        'marca', spi.marca,
        'categoria', spi.categoria,
        'quantidade', spi.quantidade,
        'preco_unitario', spi.preco_unitario,
        'subtotal', spi.subtotal
      )
      order by spi.criado_em, spi.id
    ) as itens
    from public.shopping_pedido_itens spi
    where spi.pedido_id = sp.id
  ) si on true
  order by sp.criado_em desc, sp.numero desc;
end;
$$;

revoke all on function public.shopping_pedido_finalizar_carrinho() from public, anon, authenticated;
revoke all on function public.shopping_pedidos_cliente_listar() from public, anon, authenticated;
revoke all on function public.shopping_admin_listar_pedidos() from public, anon, authenticated;

grant execute on function public.shopping_pedido_finalizar_carrinho() to authenticated;
grant execute on function public.shopping_pedidos_cliente_listar() to authenticated;
grant execute on function public.shopping_admin_listar_pedidos() to authenticated;

comment on table public.shopping_pedidos is
  'Pedidos criados a partir do carrinho ativo. Pagamento fica para a Fase 9.';

comment on table public.shopping_pedido_itens is
  'Snapshot dos itens comprados no momento da finalizacao do pedido.';

comment on function public.shopping_pedido_finalizar_carrinho() is
  'Converte o carrinho ativo em pedido pendente de pagamento e baixa estoque por venda.';

comment on function public.shopping_pedidos_cliente_listar() is
  'Lista pedidos do usuario autenticado.';

comment on function public.shopping_admin_listar_pedidos() is
  'Lista pedidos recebidos para perfis administrativos ativos.';
